In [27]:
# importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [19]:
Advertising_Data = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/Advertising.csv')
Advertising_Data.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [20]:
Advertising_Data.shape

(200, 5)

In [21]:
x = Advertising_Data[['TV','radio','newspaper']]
y = Advertising_Data['sales']

In [22]:
# Splitting the data into training data and test data
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=100)

In [32]:
# Model training
# Linear Regression
mlr=LinearRegression()

In [33]:
# training the Linear Regression model with training data
mlr.fit(x_train, y_train)

LinearRegression()

In [36]:
print('Intercept :',mlr.intercept_)
print('Coefficient :')
list(zip(x,mlr.coef_))

Intercept : 2.6527896688794943
Coefficient :

[('TV', 0.045425596023997955),
 ('radio', 0.18975772766893614),
 ('newspaper', 0.0046030789531120745)]

In [43]:
y_pred_mlr=mlr.predict(x_test)
print('Prediction for test Set : {}'.format(y_pred_mlr))

Prediction for test Set : [10.62160072 20.00625302 16.91850882 19.17040746 20.94974131 13.12284284
 11.80740696 12.32019766 20.57806782 20.95662688 10.79096475 19.54868702
  6.42403866 15.23133391  8.97226257  7.89897862 16.23599497 12.02636477
 17.09702178 11.26080277 16.97826292  9.75655721 20.82389762 17.20916742
 15.13816239 21.97290698 19.20181841 10.07501899 19.39017185 14.8673761
 14.36798893  7.55604543  9.96742165 14.76342565  7.20995576 13.60003295
  7.49088656 11.70865932 13.46091883 15.2229793  17.18088277 13.56738329
 14.30942267 13.72909849 11.88559349  8.77039705 12.1244102  19.20252289
  9.08376601  5.15367352 16.22852749 18.14111213 12.94835466 16.86274503
 17.86462435 12.33930625  4.3575739  11.25904494 16.11560622 13.56602169]

In [41]:
mlr.df = pd.DataFrame({'Actual Value': y_test, 'Predicted Value': y_pred_mlr})
mlr.df

     Actual Value  Predicted Value
126           6.6        10.621601
104          20.7        20.006253
99           17.2        16.918509
92           19.4        19.170407
111          21.8        20.949741
167          12.2        13.122843
116          12.2        11.807407
96           11.7        12.320198
52           22.6        20.578068
69           22.3        20.956627
164          11.9        10.790965
124          19.7        19.548687
182           8.7         6.424039
154          15.6        15.231334
125          10.6         8.972263
196           9.7         7.898979
194          17.3        16.235995
177          11.7        12.026365
163          18.0        17.097022
31           11.9        11.260803
11           17.4        16.978263
73           11.0         9.756557
15           22.4        20.823898
41           17.1        17.209167
97           15.5        15.138162
128          24.7        21.972907
133          19.6        19.201818
82           11.3        10.075019
139          20.7        19.390172
123          15.2        14.867376
83           13.6        14.367989
65            9.3         7.556045
151          11.6         9.967422
162          14.9        14.763426
170           8.4         7.209956
77           14.2        13.600033
32            9.6         7.490887
173          11.7        11.708659
174          11.5        13.460919
85           15.2        15.222979
168          17.1        17.180883
112          14.1        13.567383
171          14.5        14.309423
181          12.2        13.729098
7            13.2        11.885593
46           10.6         8.770397
75            8.7        12.124410
28           18.9        19.202523
29           10.5         9.083766
195           7.6         5.153674
40           16.6        16.228527
153          19.0        18.141112
115          12.6        12.948355
64           18.0        16.862745
59           18.4        17.864624
1            10.4        12.339306
192           5.9         4.357574
136           9.5        11.259045
152          16.6        16.115606
161          13.3        13.566022

In [47]:
mlr.predict([[56,55,67]])

array([15.94170436])

In [49]:
from sklearn import metrics
meanAErr = metrics.mean_absolute_error(y_test, y_pred_mlr)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_mlr)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_mlr))
print('R squared : {:0.2f}'.format(mlr.score(x,y)*100))
print('Mean Absolute Error:',meanAErr)
print('Mean Square Error:',meanSqErr)
print('Root Mean Absulute Error:',rootMeanSqErr)

R squared : 89.59
Mean Absolute Error: 1.0638483124072033
Mean Square Error: 1.8506819941636972
Root Mean Absulute Error: 1.3603977338130555